/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACol: typeof import('ant-design-vue/es')['Col']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    ADropdownButton: typeof import('ant-design-vue/es')['DropdownButton']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BackgroundProcesser: typeof import('./src/components/BackgroundProcesser/index.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker/index.vue')['default']
    ComponentList: typeof import('./src/components/ComponentList/index.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu/index.vue')['default']
    Dragg: typeof import('./src/components/LayerList/dragg.vue')['default']
    EditGroup: typeof import('./src/components/EditGroup/index.vue')['default']
    EditWrapper: typeof import('./src/components/EditWrapper/index.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar/index.vue')['default']
    ImageProcesser: typeof import('./src/components/ImageProcesser/index.vue')['default']
    InlineEditor: typeof import('./src/components/InlineEditor/index.vue')['default']
    LayerList: typeof import('./src/components/LayerList/index.vue')['default']
    PText: typeof import('./src/components/PText/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectTable: typeof import('./src/components/SelectTable/index.vue')['default']
    ShadowPicker: typeof import('./src/components/ShadowPicker/index.vue')['default']
    TemplateList: typeof import('./src/components/TemplateList/index.vue')['default']
    Upload: typeof import('./src/components/Upload/index.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
